# [[Target]]
# url = "http://104.219.209.251/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.ace-aust.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://38.22.92.186/app/data.php"
# method = "POST"
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://45.204.214.241/data"
# method = "POST"
# # headers = { "Host" = '${choose_random:"hxtfja.work","mgttia.work","zcorae.work","nvtria.work"}' }
# headers = { "Host" = 'hxtfja.work' }
# params = { sv = '{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}' }

# [[Target]]
# url = "http://107.148.1.102/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.bjyashi.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

[[Target]]
url = "http://www.azimofis.com/app/data.php"
method = "POST"
params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

[[Target]]
url = "http://www.harvestpink.com/app/data.php"
method = "POST"
params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://www.xxx-gal.com/app/data.php"
# method = "POST"
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

[[Target]]
url = "http://www.appnursery.com/app/data.php"
method = "POST"
params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://www.fuck-mom.com/app/data.php"
# method = "POST"
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://104.219.209.57/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.limaker.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://156.245.198.60/data"
# method = "POST"
# # headers = { "Host" = '${choose_random:"hfiaoe.work","xkcief.work","wteuad.work"}' }
# headers = { "Host" = 'wteuad.work' }
# params = { sv = '{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}' }

# [[Target]]
# url = "http://38.22.92.186/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.bcdlldb.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://104.233.170.216/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.listamusical.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://154.44.30.179/api/uploads/pay2/"
# method = "GET"
# headers = { "Host" = '${choose_random:"dsxvv.top","wdcss.top","sdxcw.shop","zoxnn.shop","www.fenxz.top","www.xueoi.shop","www.rrxue.top"}' }
# params = { fa = '${random:number,100,9999999}', username = "${cn_mobile}", pay = '${random:number,100000,999999}' }

# [[Target]]
# url = "http://154.44.30.179/ddd.php"
# method = "GET"
# headers = { "Host" = '${choose_random:"dsxvv.top","wdcss.top","sdxcw.shop","zoxnn.shop","www.fenxz.top","www.xueoi.shop","www.rrxue.top"}' }
# params = { fa = '${random:number,100,9999999}', qq = "${cn_mobile}" }

# [[Target]]
# url = "http://redxx.shop/api/uploads/wx1/"
# method = "GET"
# params = { username = "${cn_mobile}", password = "${password}", ym = "${chinese_id}", bianhao = "wx", deviceType = '${choose_random:"PC电脑","ios","web"}' }

# [[Target]]
# url = "http://154.44.30.179/wx2/index.php"
# method = "GET"
# headers = { "Host" = '${choose_random:"dsxvv.top","wdcss.top","sdxcw.shop","zoxnn.shop","www.fenxz.top","www.xueoi.shop","www.rrxue.top"}' }
# params = { fa = '${random:number,100,9999999}', qq = "${cn_mobile}" }

# [[Target]]
# url = "http://154.44.30.179/cw.php"
# method = "GET"
# headers = { "Host" = '${choose_random:"dsxvv.top","wdcss.top","sdxcw.shop","zoxnn.shop","www.fenxz.top","www.xueoi.shop","www.rrxue.top"}' }
# params = { fa = '${random:number,100,9999999}', qq = "${cn_mobile}" }

# [[Target]]
# url = "http://104.233.170.55/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.din-records.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://104.233.170.217/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.ericsfreesite.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }

# [[Target]]
# url = "http://104.233.170.241/app/data.php"
# method = "POST"
# headers = { "Host" = 'www.morozakisou.com' }
# params = { sv = '${base64:${base64:`{"act":"sv","data":{"user":"${qqid}","pass":"${password}"}}`}}' }
